# Generated by Django 4.0.1 on 2022-04-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0002_department_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('subject', models.ManyToManyField(to='orm_app.Subject')),
            ],
        ),
    ]
