# Generated by Django 4.0.1 on 2022-03-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_mail', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=150)),
                ('body', models.TextField()),
            ],
        ),
    ]
